name: flutter_clean_architecture
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # Locale
  flutter_localizations:
    sdk: flutter
  intl: any

  # DI
  get_it: ^8.0.0

  # Networking
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1

  # State management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

  # Routing
  go_router: ^14.2.8

  # Shared
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2

  # Location
  geolocator: ^13.0.1

  # Utils
  equatable: ^2.0.5

  # Local db
  drift: ^2.20.2
  drift_flutter: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.5.7
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.2
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.1
  drift_dev: ^2.20.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/launcher_icon/
    - assets/icons/

flutter_native_splash:
  background_image: "assets/splash_screen/background.png"
  image: "assets/splash_screen/logo.png"
  android_12:
    image: "assets/splash_screen/logo.png"
